export default {
  SM: {
    name: 'Skeletal Man',
    alterEgo: 'John T. Gill, MD',
    image: 'https://via.placeholder.com/200x400?text=Hero',
    intro: 'Introducing the co-leader of the OrthoPAC Squad! The Skeletal One’s specialty is fundraising for personal contributions that help elect and re-elect champions of MSK care.',
    superPower: 'Flight',
    sourceOfPower: 'Skeletal Man is propelled by the participation of our team! The more OrthoPAC members we have on board, the stronger he becomes. Last cycle, we were over 5,000 members strong — and growing! This year, he’s stronger than ever, seeing our PAC grow by 15% just last election cycle.',
    randomFact: 'Both he and the OrthoPAC are celebrating their 20th birthday this year.',
    villainName: 'The Red Tape Mummy',
    villainIntro: 'Wielding the fearsome power of over-regulation, RTM makes things stickier and more complicated, drowning people in paperwork and making a convoluted mess of everything.',
    villainImage: 'https://via.placeholder.com/200x200?text=Villian',
  },
  LL: {
    name: 'Lady Ligament',
    alterEgo: 'Kristy Weber, MD',
    image: 'https://via.placeholder.com/200x400?text=Hero',
    intro: 'Stretching PAC contributions is this lady’s game! As the co-leader of the OrthoPac squad. She raises funding from specialty and group practices, using corporate dollars to expand the AAOS presence & political footprint.',
    superPower: 'Elasticity',
    motivations: 'Lady Ligament lives to grow our PAC presence.',
    randomFact: 'She runs our Advisor\'s Circle program, now 19 groups strong!',
    duties: ' This fundraising fem-nomenon functions on the federal and state level, enabling our PAC to participate in governors and state political committees, as well as helping elect officials through independent expenditures.',
    villainName: 'Reckless Rubberstamper ',
    villainIntro: 'This aggressive authorizer is mis-guided, mis-informed and malevolent. Her rampant rubber-stamping results far too often in the passing of fatally flawed laws.',
    villainImage: 'https://via.placeholder.com/200x200?text=Villian',
  },
  AA: {
    name: 'Ancillary Annie',
    alterEgo: 'Ann Ownership',
    image: 'https://via.placeholder.com/200x400?text=Hero',
    intro: 'Introducing the co-leader of the OrthoPAC Squad! The Skeletal One’s specialty is fundraising for personal contributions that help elect and re-elect champions of MSK care.',
    superPower: 'Flight',
    sourceOfPower: 'Skeletal Man is propelled by the participation of our team! The more OrthoPAC members we have on board, the stronger he becomes. Last cycle, we were over 5,000 members strong — and growing! This year, he’s stronger than ever, seeing our PAC grow by 15% just last election cycle.',
    randomFact: 'Both he and the OrthoPAC are celebrating their 20th birthday this year.',
    villainName: 'The Red Tape Mummy',
    villainIntro: 'Wielding the fearsome power of over-regulation, RTM makes things stickier and more complicated, drowning people in paperwork and making a convoluted mess of everything.',
    villainImage: 'https://via.placeholder.com/200x200?text=Villian',

  },
  MM: {
    name: 'Mighty Microscope',
    alterEgo: 'Rhea Search',
    image: 'https://via.placeholder.com/200x400?text=Hero',
    intro: 'Introducing the co-leader of the OrthoPAC Squad! The Skeletal One’s specialty is fundraising for personal contributions that help elect and re-elect champions of MSK care.',
    superPower: 'Flight',
    sourceOfPower: 'Skeletal Man is propelled by the participation of our team! The more OrthoPAC members we have on board, the stronger he becomes. Last cycle, we were over 5,000 members strong — and growing! This year, he’s stronger than ever, seeing our PAC grow by 15% just last election cycle.',
    randomFact: 'Both he and the OrthoPAC are celebrating their 20th birthday this year.',
    villainName: 'Miss Government',
    villainIntro: 'Wielding the fearsome power of over-regulation, RTM makes things stickier and more complicated, drowning people in paperwork and making a convoluted mess of everything.',
    villainImage: 'https://via.placeholder.com/200x200?text=Villian',

  },
  SS: {
    name: 'Super Specialty',
    image: 'https://via.placeholder.com/200x400?text=Hero',
    intro: 'Introducing the co-leader of the OrthoPAC Squad! The Skeletal One’s specialty is fundraising for personal contributions that help elect and re-elect champions of MSK care.',
    superPower: 'Flight',
    sourceOfPower: 'Skeletal Man is propelled by the participation of our team! The more OrthoPAC members we have on board, the stronger he becomes. Last cycle, we were over 5,000 members strong — and growing! This year, he’s stronger than ever, seeing our PAC grow by 15% just last election cycle.',
    randomFact: 'Both he and the OrthoPAC are celebrating their 20th birthday this year.',
    villainName: 'The Red Tape Mummy',
    villainIntro: 'Wielding the fearsome power of over-regulation, RTM makes things stickier and more complicated, drowning people in paperwork and making a convoluted mess of everything.',
    villainImage: 'https://via.placeholder.com/200x200?text=Villian',

  },
  RR: {
    name: 'The Radical Reformer',
    alterEgo: 'Justus James',
    image: 'https://via.placeholder.com/200x400?text=Hero',
    intro: 'Introducing the co-leader of the OrthoPAC Squad! The Skeletal One’s specialty is fundraising for personal contributions that help elect and re-elect champions of MSK care.',
    superPower: 'Flight',
    sourceOfPower: 'Skeletal Man is propelled by the participation of our team! The more OrthoPAC members we have on board, the stronger he becomes. Last cycle, we were over 5,000 members strong — and growing! This year, he’s stronger than ever, seeing our PAC grow by 15% just last election cycle.',
    randomFact: 'Both he and the OrthoPAC are celebrating their 20th birthday this year.',
    villainName: 'The Red Tape Mummy',
    villainIntro: 'Wielding the fearsome power of over-regulation, RTM makes things stickier and more complicated, drowning people in paperwork and making a convoluted mess of everything.',
    villainImage: 'https://via.placeholder.com/200x200?text=Villian',
  }
}
